### ISSUE TITLE
Some tiles not rendering in the correct positions

### ISSUE THREAD

**Issue by mattbruv** [TheOnlyZac/ccsr-map-viewer#3]
Some tiles are not rendering in the correct positions. I haven't looked into why this is the case, but I'm making the issue for now.

> Python 3.10.4
> pygame Version: 2.1.2

![0101_1](https://user-images.githubusercontent.com/5638426/191602532-bfab1f66-f76c-4c3a-8b36-8d441a8470a6.png)

vs. 

![image](https://user-images.githubusercontent.com/5638426/191604981-5d8a2eb2-3794-4d24-94fd-b4184cf79ead.png)

![0505_1](https://user-images.githubusercontent.com/5638426/191602633-28ffa61e-15aa-4b2b-b456-76ca20ffb0d9.png)

vs.

![image](https://user-images.githubusercontent.com/5638426/191605275-cf666dd3-9fab-4c91-8ff5-4e306f5d31dd.png)

**Comment by TheOnlyZac** [comment]
Thanks for opening this issue! Yeah, this is one of the major hurdles I ran into with the renderer. I did have a look though the tile properties in Director, and I recall something along the lines of some blocks having special size/position values so they end up being stretched and/or not perfectly aligned with the tile grid, but I couldn't figure out where it pulls those values from.
